### ISSUE TITLE
Rust - thread panic at byte index ###

### ISSUE THREAD

**Issue by stacy-l** [PacificBiosciences/trgt#10]
Hello,

I'm trying to run trgt on a few samples. I'm using snakemake to manage each call to trgt, and although each job is marked "complete" (output files generated), this error prints to console:

```
thread '<unnamed>' panicked at 'byte index 18446744073709551608 is out of bounds of `TGAAAGCTACCTGAGTGATTCCAAAAATGCCTGTTCTCTTTTACACACACACACACACACGCACACACACACGCGTGCGTGCACACAAACACACACGCACACCTGCCAGCTCAGGCAATCTCATTTTCTTCACCTAAGTCTTCAGCCACCATTTACTTCTCTGATAACATCCAAATCTCTGTCTTCAGACACATTTCAGACTGTTCAAGGGGCATCTCTAGAGAGATGCCATATACTAAATCCCAAATTTGTTTTC`[...]', src/workflows/get_spanning.rs:48:27
stack backtrace:
   0:           0x633c50 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:           0x633c50 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x633c50 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:           0x633c50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:           0x70d0ae - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:           0x631065 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:           0x633a15 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:           0x633a15 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:           0x6352cf - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:           0x63500a - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:           0x6359c8 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:           0x635767 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:           0x6340fc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:           0x635482 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:           0x40d083 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:           0x710e8b - core::str::slice_error_fail_rt::h8255edb68a71f85c
  16:           0x40d4a7 - core::str::slice_error_fail::h22ef6191a554ebc1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/str/mod.rs:86:9
  17:           0x44815a - trgt::workflows::get_spanning::get_spanning::hd58231e8c996ceb0
  18:           0x428e44 - trgt::workflows::tr::analyze::h12b3d70f1cbf4f80
  19:           0x449049 - <F as threadpool::FnBox>::call_box::h9e66f0da6d8bcc06
  20:           0x4dab63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h44404a4c5f4111a7
  21:           0x4d8ae3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf8f515a3bee6a1bc
  22:           0x638073 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  23:           0x638073 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  24:           0x638073 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  25:           0x64d203 - start_thread
                               at /mnt/tc-build/src/glibc-2.17/nptl/pthread_create.c:308:7
  26:           0x6c5df9 - __clone
                               at /mnt/tc-build/src/glibc-2.17/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113
  27:                0x0 - <unknown>
```

I've performed a few different runs, and the error message's byte index is the same each time. I'm attaching a few files for reference:
* [20230801_TRGT_errorlog.txt](https://github.com/PacificBiosciences/trgt/files/12233531/20230801_TRGT_errorlog.txt): A text file with the printed error (same as code block above, but might be easier to share with others)
* [20230801_TRGT_snakemakelog.txt](https://github.com/PacificBiosciences/trgt/files/12233532/20230801_TRGT_snakemakelog.txt): The snakemake log for the run. Doesn't show the printer error, but does show each call to trgt.
* [trgt_snakemake.txt](https://github.com/PacificBiosciences/trgt/files/12233539/trgt_snakemake.txt): The rule file used to specify calls to trgt.
* [trgt_conda.txt](https://github.com/PacificBiosciences/trgt/files/12233538/trgt_conda.txt): The config file for creating the environment used to run trgt in snakemake.

I can provide the specs for the HPC node that I'm using as well, if that's helpful.

Many thanks in advance for your help :)

**Comment by egor-dolzhenko** [comment]
Apologies about the error. Would you be up for testing the new version of TRGT (not yet released) on these samples? If yes, let's connect by [email](mailto:edolzhenko@pacificbiosciences.com)?

**Comment by stacy-l** [comment]
Sure, I'll send you an email in a moment. :)
